Repository movester/mymovester-api, pull requests merged in 2024-05, with the labels that each got.

#48 루틴 폴더 복제 API 구현
  apps/mymovester-api/src/routine/routine.controller.ts
  apps/mymovester-api/src/routine/routine.service.ts
Labels: feature

#47 루틴 폴더 삭제 API 구현
  apps/mymovester-api/src/routine/routine.controller.ts
  apps/mymovester-api/src/routine/routine.request.ts
  apps/mymovester-api/src/routine/routine.service.ts
  libs/common/src/util.ts
  libs/persistence/src/domain/routine/entity/routine.entity.ts
  libs/persistence/src/domain/routine/repository/routine.repository.ts
  libs/persistence/src/domain/user/repository/user.repository.ts
Labels: feature

#49 응답형식 모듈만들기
  apps/mymovester-api/src/auth/auth.controller.ts
  apps/mymovester-api/src/auth/kakao.service.ts
  apps/mymovester-api/src/like/like.controller.ts
  apps/mymovester-api/src/like/like.service.ts
  apps/mymovester-api/src/main.ts
  apps/mymovester-api/src/routine/routine.controller.ts
  apps/mymovester-api/src/routine/routine.service.ts
  apps/mymovester-api/src/stretching/request/get-stretching-list.request.ts
  apps/mymovester-api/src/stretching/stretching.controller.ts
  apps/mymovester-api/src/user/user.controller.ts
  apps/mymovester-api/src/user/user.service.ts
  libs/common/src/exception/http-exception.filter.ts
  libs/common/src/response/default.response.ts
  libs/common/src/sentry.interceptor.ts
  libs/common/src/webhook.interceptor.ts
Labels: feature

#50 루틴 폴더 수정 API 구현
  .eslintrc.js
  apps/mymovester-api/src/config/swagger.ts
  apps/mymovester-api/src/main.ts
  apps/mymovester-api/src/routine/routine.controller.ts
  apps/mymovester-api/src/routine/routine.module.ts
  apps/mymovester-api/src/routine/routine.request.ts
  apps/mymovester-api/src/routine/routine.service.ts
  apps/mymovester-api/src/user/response/user.response.ts
  apps/mymovester-api/src/user/user.service.ts
  libs/common/src/response/default.response.ts
  libs/persistence/src/domain/routine/repository/routine.repository.ts
  libs/persistence/src/domain/user/repository/user.repository.ts
  tsconfig.json
Labels: feature

#51 스트레칭 조회 쿼리 최적화
  apps/mymovester-api/src/like/like.service.ts
  apps/mymovester-api/src/stretching/stretching.service.ts
  libs/persistence/src/domain/stretching/entity/stretching-effect.entity.ts
  libs/persistence/src/domain/stretching/entity/stretching-image.entity.ts
  libs/persistence/src/domain/stretching/entity/stretching-precaution.entity.ts
  libs/persistence/src/domain/stretching/entity/stretching-technique.entity.ts
  libs/persistence/src/domain/stretching/entity/stretching.entity.ts
  libs/persistence/src/domain/stretching/repository/stretching.repository.ts
Labels: fix

#55 swagger url 설정
  apps/backoffice-api/src/stretching/stretching.controller.ts
  apps/mymovester-api/src/config/swagger.ts
  apps/mymovester-api/src/mymovester.module.ts
Labels: 🫅 Product, ⚙ Setting

#56 Feature/swagger 설정
  apps/mymovester-api/src/config/swagger.ts
Labels: 🫅 Product, ⚙ Setting, 🧪 Test

#57 swagger 경로 수정
  apps/mymovester-api/src/config/swagger.ts
Labels: 🫅 Product, ✨ Feature, 🧪 Test

#58 핫 리로딩 추가
  .env.example
  apps/mymovester-api/src/main.ts
  package-lock.json
  package.json
  webpack-hmr.config.js
Labels: 🫅 Product, ⚙ Setting

#59 스트레칭 리스트 조회시 효과 필터 오류 해결
  libs/persistence/src/domain/stretching/repository/stretching.repository.ts
Labels: 🫅 Product, 🚨 Emergency, 🐞 BugFix

#60 인터페이스 레이어 만들기
  apps/backoffice-api/src/backoffice.module.ts
  apps/mymovester-api/src/like/like.controller.ts
  apps/mymovester-api/src/like/like.interface.ts
  apps/mymovester-api/src/like/like.module.ts
  apps/mymovester-api/src/like/like.service.ts
  apps/mymovester-api/src/routine/routine.controller.ts
  apps/mymovester-api/src/routine/routine.interface.ts
  apps/mymovester-api/src/routine/routine.module.ts
  apps/mymovester-api/src/routine/routine.service.ts
  apps/mymovester-api/src/stretching/stretching.controller.ts
  apps/mymovester-api/src/stretching/stretching.interface.ts
  apps/mymovester-api/src/stretching/stretching.module.ts
  apps/mymovester-api/src/stretching/stretching.service.ts
  apps/mymovester-api/src/user/user.controller.ts
  apps/mymovester-api/src/user/user.interface.ts
  apps/mymovester-api/src/user/user.module.ts
  apps/mymovester-api/src/user/user.service.ts
Labels: 🫅 Product, 🔨 Refactor

#61 Feature/루틴 스트레칭 추가
  apps/mymovester-api/src/auth/auth.module.ts
  apps/mymovester-api/src/mymovester.module.ts
  apps/mymovester-api/src/routine/routine.controller.ts
  apps/mymovester-api/src/routine/routine.interface.ts
  apps/mymovester-api/src/routine/routine.module.ts
  apps/mymovester-api/src/routine/routine.request.ts
  apps/mymovester-api/src/routine/routine.service.ts
  libs/persistence/src/domain/routine/entity/routine-stretching.entity.ts
  libs/persistence/src/domain/routine/entity/routine.entity.ts
  libs/persistence/src/domain/routine/repository/routine-item.repository.ts
  libs/persistence/src/domain/routine/repository/routine.repository.ts
Labels: 🫅 Product, ✨ Feature
